groups:
  - name: example
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode='idle'}[5m])) * 100) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High CPU usage detected
          description: 'Instance {{ $labels.instance }} CPU usage is above 90%.'
          #testingfg

