name: Deploy Grafana Alerting Rules and Alertmanager Configuration



on:

  push:

    branches:

      - main

    paths:

      - 'rules.yaml'

      - 'alertmanager.yml'



jobs:

  deploy:

    runs-on: ubuntu-latest



    steps:

      - name: Checkout repository

        uses: actions/checkout@v2



      - name: Set up Grafana CLI

        run: |

          curl -sSLf https://dl.grafana.com/oss/release/grafana-cli-linux-amd64.tar.gz | tar -xz -C /usr/local/bin

          chmod +x /usr/local/bin/grafana-cli



      - name: Deploy alerting rules to Grafana Mimir

        run: |

          grafana-cli plugins install grafana-mimir

          mimirtool rules load rules.yaml

        env:

          MIMIR_URL: ${{ secrets.MIMIR_URL }}

          MIMIR_API_KEY: ${{ secrets.MIMIR_API_KEY }}

          TENANT_ID: ${{ secrets.TENANT_ID }}



      - name: Deploy Alertmanager configuration

        run: |

          curl -X POST -H "Authorization: Bearer ${{ secrets.MIMIR_API_KEY }}" \

            -H "X-Scope-OrgID: ${{ secrets.TENANT_ID }}" \

            -F "file=@alertmanager.yml" \

            ${{ secrets.MIMIR_URL }}/api/v1/alertmanager/config
